blank_issues_enabled: false
contact_links:
    - name: Feature Request
      url: https://github.com/RooVetGit/Bee-Cline/discussions/categories/feature-requests
      about: Share and vote on feature requests for Bee Cline
    - name: Leave a Review
      url: https://marketplace.visualstudio.com/items?itemName=RooVeterinaryInc.bee-cline&ssr=false#review-details
      about: Enjoying Bee Cline? Leave a review here!
